services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: edio
      MYSQL_USER: manager
      MYSQL_PASSWORD: manager0
      MYSQL_ROOT_PASSWORD: manager0
      TZ: Asia/Seoul
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql" ]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./db/init/conf.d:/etc/mysql/conf.d
      - ./db/init/init.d:/docker-entrypoint-initdb.d
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app
    entrypoint: >
      sh -c "./gradlew bootRun"
networks:
  app-network:
    driver: bridge
