spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://ec2-3-38-251-128.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google
#            redirect-uri: http://localhost:3000
