jwt:
  expiration-time: '3600000'
  refresh-expiration-time: '86400000'
  secret: ${jwt.secret}
spring:
  security:
    oauth2:
      client:
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            scope: profile,email
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: '300000'
      maximum-pool-size: '10'
      connection-timeout: '60000'
      initialization-fail-timeout: '30000'
      max-lifetime: '1800000'
      minimum-idle: '5'
    password: ${spring.datasource.password}
    username: ${spring.datasource.username}
    url: ${spring.datasource.url}
  application:
    name: edio_backend
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 100MB
logging:
  level:
    root: INFO
